[2024-01-02T17:44:10.112+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 24_01_02_fx_mkt_data.first_attempt manual__2024-01-02T17:44:04.325340+00:00 [queued]>
[2024-01-02T17:44:10.145+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 24_01_02_fx_mkt_data.first_attempt manual__2024-01-02T17:44:04.325340+00:00 [queued]>
[2024-01-02T17:44:10.146+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2024-01-02T17:44:10.196+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): first_attempt> on 2024-01-02 17:44:04.325340+00:00
[2024-01-02T17:44:10.214+0000] {standard_task_runner.py:57} INFO - Started process 1795 to run task
[2024-01-02T17:44:10.224+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', '24_01_02_fx_mkt_data', 'first_attempt', 'manual__2024-01-02T17:44:04.325340+00:00', '--job-id', '201', '--raw', '--subdir', 'DAGS_FOLDER/get_fx_mkt_data.py', '--cfg-path', '/tmp/tmpfo4zvpq4']
[2024-01-02T17:44:10.230+0000] {standard_task_runner.py:85} INFO - Job 201: Subtask first_attempt
[2024-01-02T17:44:10.476+0000] {task_command.py:416} INFO - Running <TaskInstance: 24_01_02_fx_mkt_data.first_attempt manual__2024-01-02T17:44:04.325340+00:00 [running]> on host ff92cbb9a252
[2024-01-02T17:44:10.906+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='24_01_02_fx_mkt_data' AIRFLOW_CTX_TASK_ID='first_attempt' AIRFLOW_CTX_EXECUTION_DATE='2024-01-02T17:44:04.325340+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-02T17:44:04.325340+00:00'
[2024-01-02T17:44:10.910+0000] {oandapyV20.py:207} INFO - setting up API-client for environment practice
[2024-01-02T17:44:12.740+0000] {logging_mixin.py:154} INFO - Error processing AUD_USD: fetch_data() got an unexpected keyword argument 'interval'
[2024-01-02T17:44:12.742+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-02T17:44:12.811+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=24_01_02_fx_mkt_data, task_id=first_attempt, execution_date=20240102T174404, start_date=20240102T174410, end_date=20240102T174412
[2024-01-02T17:44:13.005+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-02T17:44:13.095+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
