[2024-01-02T19:18:09.409+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 24_01_02_fx_mkt_data.first_attempt manual__2024-01-02T19:18:04.737221+00:00 [queued]>
[2024-01-02T19:18:09.451+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 24_01_02_fx_mkt_data.first_attempt manual__2024-01-02T19:18:04.737221+00:00 [queued]>
[2024-01-02T19:18:09.452+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2024-01-02T19:18:09.508+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): first_attempt> on 2024-01-02 19:18:04.737221+00:00
[2024-01-02T19:18:09.528+0000] {standard_task_runner.py:57} INFO - Started process 3028 to run task
[2024-01-02T19:18:09.540+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', '24_01_02_fx_mkt_data', 'first_attempt', 'manual__2024-01-02T19:18:04.737221+00:00', '--job-id', '222', '--raw', '--subdir', 'DAGS_FOLDER/get_fx_mkt_data.py', '--cfg-path', '/tmp/tmpqmz_k0qe']
[2024-01-02T19:18:09.549+0000] {standard_task_runner.py:85} INFO - Job 222: Subtask first_attempt
[2024-01-02T19:18:09.833+0000] {task_command.py:416} INFO - Running <TaskInstance: 24_01_02_fx_mkt_data.first_attempt manual__2024-01-02T19:18:04.737221+00:00 [running]> on host ff92cbb9a252
[2024-01-02T19:18:10.245+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='24_01_02_fx_mkt_data' AIRFLOW_CTX_TASK_ID='first_attempt' AIRFLOW_CTX_EXECUTION_DATE='2024-01-02T19:18:04.737221+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-02T19:18:04.737221+00:00'
[2024-01-02T19:18:10.249+0000] {oandapyV20.py:207} INFO - setting up API-client for environment practice
[2024-01-02T19:18:11.420+0000] {logging_mixin.py:154} INFO - vendor id: 6, vendor name: oanda
[2024-01-02T19:18:11.443+0000] {oandapyV20.py:261} INFO - performing request https://api-fxpractice.oanda.com/v3/instruments/AUD_USD/candles
[2024-01-02T19:18:12.084+0000] {oandapyV20.py:261} INFO - performing request https://api-fxpractice.oanda.com/v3/instruments/AUD_USD/candles
[2024-01-02T19:18:14.855+0000] {logging_mixin.py:154} INFO - 3570
[2024-01-02T19:18:15.656+0000] {logging_mixin.py:154} INFO - Error processing AUD_USD: (psycopg2.errors.NotNullViolation) null value in column "data_vendor_id" of relation "security_daily_price" violates not-null constraint
DETAIL:  Failing row contains (46686, null, 2024-01-02 19:18:06.037748, 2024-01-02 19:18:06.037896, 2010-12-29 22:00:00, null, null, null, null, 14112).

[SQL: INSERT INTO security_daily_price (security_id, created, updated, date, volume) VALUES (%(security_id)s, %(created)s, %(updated)s, %(date)s, %(volume)s)]
[parameters: ({'security_id': 46686, 'created': datetime.datetime(2024, 1, 2, 19, 18, 6, 37748), 'updated': datetime.datetime(2024, 1, 2, 19, 18, 6, 37896), 'date': Timestamp('2010-12-29 22:00:00+0000', tz='UTC'), 'volume': 14112}, {'security_id': 46686, 'created': datetime.datetime(2024, 1, 2, 19, 18, 6, 37748), 'updated': datetime.datetime(2024, 1, 2, 19, 18, 6, 37896), 'date': Timestamp('2010-12-30 22:00:00+0000', tz='UTC'), 'volume': 11245}, {'security_id': 46686, 'created': datetime.datetime(2024, 1, 2, 19, 18, 6, 37748), 'updated': datetime.datetime(2024, 1, 2, 19, 18, 6, 37896), 'date': Timestamp('2011-01-01 22:00:00+0000', tz='UTC'), 'volume': 434}, {'security_id': 46686, 'created': datetime.datetime(2024, 1, 2, 19, 18, 6, 37748), 'updated': datetime.datetime(2024, 1, 2, 19, 18, 6, 37896), 'date': Timestamp('2011-01-02 22:00:00+0000', tz='UTC'), 'volume': 9509}, {'security_id': 46686, 'created': datetime.datetime(2024, 1, 2, 19, 18, 6, 37748), 'updated': datetime.datetime(2024, 1, 2, 19, 18, 6, 37896), 'date': Timestamp('2011-01-03 22:00:00+0000', tz='UTC'), 'volume': 19899}, {'security_id': 46686, 'created': datetime.datetime(2024, 1, 2, 19, 18, 6, 37748), 'updated': datetime.datetime(2024, 1, 2, 19, 18, 6, 37896), 'date': Timestamp('2011-01-04 22:00:00+0000', tz='UTC'), 'volume': 22346}, {'security_id': 46686, 'created': datetime.datetime(2024, 1, 2, 19, 18, 6, 37748), 'updated': datetime.datetime(2024, 1, 2, 19, 18, 6, 37896), 'date': Timestamp('2011-01-05 22:00:00+0000', tz='UTC'), 'volume': 17923}, {'security_id': 46686, 'created': datetime.datetime(2024, 1, 2, 19, 18, 6, 37748), 'updated': datetime.datetime(2024, 1, 2, 19, 18, 6, 37896), 'date': Timestamp('2011-01-06 22:00:00+0000', tz='UTC'), 'volume': 20265}  ... displaying 10 of 3570 total bound parameter sets ...  {'security_id': 46686, 'created': datetime.datetime(2024, 1, 2, 19, 18, 6, 37748), 'updated': datetime.datetime(2024, 1, 2, 19, 18, 6, 37896), 'date': Timestamp('2023-12-28 22:00:00+0000', tz='UTC'), 'volume': 41818}, {'security_id': 46686, 'created': datetime.datetime(2024, 1, 2, 19, 18, 6, 37748), 'updated': datetime.datetime(2024, 1, 2, 19, 18, 6, 37896), 'date': Timestamp('2024-01-01 22:00:00+0000', tz='UTC'), 'volume': 48146})]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
[2024-01-02T19:18:15.657+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-02T19:18:15.725+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=24_01_02_fx_mkt_data, task_id=first_attempt, execution_date=20240102T191804, start_date=20240102T191809, end_date=20240102T191815
[2024-01-02T19:18:15.846+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-02T19:18:15.945+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
